feat: add random delay to login flow
ory/kratos pull request #1088
Opened 2021-02-24 17:16 UTC by mattbonnell

## Related issue
Closes #832 @aeneasr 

## Proposed changes

Adds a configurable randomized delay to the login flow to mitigate timing attacks (as specified in #832 

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

## Further comments

2021-02-24 22:31 UTC, zepatrik requested changes
I think it would make sense to use the config values introduced by #803 instead. Can you base your changes off of the v0.6 branch?

2021-02-24 22:35 UTC, mbonnell-wish commented
> I think it would make sense to use the config values introduced by #803 instead. Can you base your changes off of the v0.6 branch?

Sure thing, which config values are you referring to specifically? I looked through that PR to find some but couldn't find any related to time specifically.

2021-02-24 22:47 UTC, mattbonnell commented
> I think it would make sense to use the config values introduced by #803 instead. Can you base your changes off of the v0.6 branch?

Sure thing, which config values specifically?

2021-02-25 07:45 UTC, zepatrik commented
An sorry I linked the wrong PR, it is #961
It is not merged on master yet but on the v0.6 branch

2021-02-25 08:05 UTC, aeneasr commented
Ah - sorry - it makes sense to have master as the upstream branch, not the 0.6 - they have many merge conflicts and are a bit outdated!

2021-02-25 08:12 UTC, zepatrik commented
But half of the changes are done there already?

2021-02-25 08:56 UTC, aeneasr commented
Ah, you're right @zepatrik

2021-02-25 12:02 UTC, mattbonnell commented
Question for you @aeneasr: in #832, you said we should add the random delay whether the user exists or not, but I’m a bit confused by that. Won’t that make the “user does exist flow” take twice as long as the “user doesn’t exist”, leaving us vulnerable to timing attacks? Shouldn’t we only add the delay when the user doesn’t exist, before returning error? Maybe I’m missing something there.

2021-02-25 14:23 UTC, zepatrik commented
Agree @mattbonnell 
The goal would be for requests to take the same time regardless whether the identifier exists and also avoid hashing if necessary (because resources :moneybag:).

2021-02-25 15:19 UTC, mattbonnell commented
@zepatrik made the updates as discussed here 👍 

By the way, the go.mod seems broken on `v0.6`. To get it working locally I have to call `go get ./...`, I left go.mod/go.sum changes out because go.sum modifications seem to cause CI to fail as well, though.

2021-02-25 16:11 UTC, aeneasr commented
Yeah that's possible - 0.6 is currently in a broken CI stage. Thank you for the changes, they look really good! Maybe we can also add a test for this? :)

2021-02-25 16:25 UTC, mattbonnell commented
> Yeah that's possible - 0.6 is currently in a broken CI stage. Thank you for the changes, they look really good! Maybe we can also add a test for this? :)

added a test for the RandomDelay utility function that I introduce here; let me know if there are other tests you'd like added

2021-02-28 13:19 UTC, zepatrik requested changes

2021-02-28 13:19 UTC, zepatrik commented on x/time_test.go
> +	delay := time.Now().Sub(start)
```suggestion
	delay := time.Since(start)
```
`gosimple` will complain otherwise :wink:

2021-02-28 14:54 UTC, mattbonnell commented on x/time_test.go
> +	delay := time.Now().Sub(start)
thanks, fixed!

2021-02-28 16:05 UTC, zepatrik approved these changes

2021-03-01 17:35 UTC, aeneasr commented
Sorry to be that guy 😓 but I think we need a proper e2e test that checks this. Otherwise chances are high that this will break or regress in the future. The easiest would be to add a test case here:

1. https://github.com/ory/kratos/blob/master/selfservice/strategy/password/login_test.go#L230

Basically you check if the request is taking at least the configured amount of time - that should be enough to ensure this behavior does not regress in the future

Thank you!

2021-03-01 18:55 UTC, mattbonnell commented
> Sorry to be that guy 😓 but I think we need a proper e2e test that checks this. Otherwise chances are high that this will break or regress in the future. The easiest would be to add a test case here:
> 
> 1. https://github.com/ory/kratos/blob/master/selfservice/strategy/password/login_test.go#L230
> 
> Basically you check if the request is taking at least the configured amount of time - that should be enough to ensure this behavior does not regress in the future
> 
> Thank you!

Coming right up!

2021-03-02 14:12 UTC, mattbonnell commented
@aeneasr added

2021-03-02 16:33 UTC, aeneasr approved these changes
Great job @mattbonnell, thank you! :)

2021-03-02 16:33 UTC, merged