docs: fix stub error example
ory/kratos pull request #1642
Opened 2021-08-10 17:22 UTC by vinckr

closes https://github.com/ory/kratos/issues/1568

## Related issue(s)

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

## Further Comments

2021-08-10 19:25 UTC, aeneasr requested changes

2021-08-10 19:25 UTC, aeneasr commented on docs/docs/self-service/flows/user-facing-errors.md
> +  "error": [
Error without the JSON array :)

2021-08-11 13:24 UTC, vinckr commented on docs/docs/self-service/flows/user-facing-errors.md
> +  "error": [
ah missed that, 
done 👍

2021-08-11 13:32 UTC, aeneasr approved these changes

2021-08-11 13:32 UTC, merged