Update node.txt
ory/kratos pull request #1644
Opened 2021-08-12 12:56 UTC by weivall

fix: naming of createSelfServiceLogoutUrlForBrowsers

"@ory/kratos-client": "^0.7.1-alpha.1" doesn't have function **createSelfServiceLogoutUrlForBrowsers**. Renamed  createSelfServiceLogoutUrlForBrowsers to createSelfServiceLogout**Flow**UrlForBrowsers

## Related issue(s)

## Checklist

- [ x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [ x] I have read the [security policy](../security/policy).
- [ x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ x] I have added or changed [the documentation](docs/docs).

## Further Comments

2021-08-17 06:24 UTC, aeneasr requested changes
Thank you very much for your contribution to the documentation! Due to the way [Docusaurus](https://docusaurus.io) versioning works, you need to make the changes in two locations:

- `docs/versioned_docs/version-v{version}/path/to/file`
- `docs/docs/path/to/file`

Without making them in both locations, the changes will most likely be lost when releasing another version. Thank you! :)

2021-08-18 03:23 UTC, weivall commented
> Thank you very much for your contribution to the documentation! Due to the way [Docusaurus](https://docusaurus.io) versioning works, you need to make the changes in two locations:
> 
> * `docs/versioned_docs/version-v{version}/path/to/file`
> * `docs/docs/path/to/file`
> 
> Without making them in both locations, the changes will most likely be lost when releasing another version. Thank you! :)

Thank you! I will check it!

2021-08-23 12:16 UTC, aeneasr commented
@vinckr maybe you can help out?

2021-08-24 06:50 UTC, weivall commented
https://github.com/ory/kratos/pull/1676 @aeneasr @vinckr 
I've open an another PR

2021-08-24 09:17 UTC, aeneasr commented
#1676 :)

2021-08-24 09:17 UTC, closed without merging