feat: allow registration to be disabled
ory/kratos pull request #2081
Opened 2021-12-22 20:17 UTC by nrutherford

This feature is to allow disabling of registration flows for all methods.

## Related issue(s)

#882

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

2021-12-23 06:23 UTC, nrutherford commented
Not sure why the 1 login e2e test failed or what the docker image scanner has a problem with

2021-12-25 22:13 UTC, aeneasr requested changes
Thank you for the contribution! I think this is going into the right direction.

It would be awesome if you could add tests for this feature! :relieved:

Tests are important to open source projects because the allow reviewers to better judge if the changes are doing what was intended. They also ensure that your changes never regress / break when someone else works on code that is related to this.

If you need help with the tests feel free to push your work in progress and ping myself or another maintainer :raising_hand:

2021-12-25 22:14 UTC, aeneasr commented
> Not sure why the 1 login e2e test failed or what the docker image scanner has a problem with

That's just the CI :) We can merge without those two passing!

2021-12-26 15:25 UTC, nrutherford commented
I've added basic unit tests for registration flow. Should I look at adding a new e2e test to cover registration after oidc login?

2021-12-26 15:29 UTC, aeneasr commented
> @aeneasr I've added basic unit tests for registration flow. Should I look at adding a new e2e test to cover registration after oidc login?

Yes please :)

2021-12-26 19:57 UTC, nrutherford commented
@aeneasr I added the e2e test, please take a look when you can... first time using cypress...

2021-12-27 18:00 UTC, aeneasr approved these changes
Great, thank you so much!

2021-12-27 18:01 UTC, merged

2022-01-04 13:57 UTC, vinckr commented
Hello @nrutherford
Congrats on merging your first PR in Ory 🎉 !
Your contribution is helping secure millions of identities around the globe 🌏 
As a small token of appreciation we send all our first time contributors a gift package to welcome them to the community. 
[Please drop me an email to claim your Ory swag!](mailto:vincent@ory.sh)