obvious typo
ory/kratos pull request #2114
Opened 2022-01-06 19:36 UTC by mritalian

2022-01-06 19:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/kratos?pullRequest=2114) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/kratos?pullRequest=2114) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/kratos?pullRequest=2114) it.</sub>

2022-01-06 20:55 UTC, aeneasr requested changes
Thank you very much for your contribution to the documentation! Due to the way [Docusaurus](https://docusaurus.io) versioning works, you need to make the changes in two locations:

- `docs/versioned_docs/version-v{version}/path/to/file`
- `docs/docs/path/to/file`

Without making them in both locations, the changes will most likely be lost when releasing another version. Thank you! :)

2022-01-06 22:08 UTC, mritalian commented
> Thank you very much for your contribution to the documentation! Due to the way [Docusaurus](https://docusaurus.io) versioning works, you need to make the changes in two locations:
> 
> * `docs/versioned_docs/version-v{version}/path/to/file`
> * `docs/docs/path/to/file`
> 
> Without making them in both locations, the changes will most likely be lost when releasing another version. Thank you! :)

Makes sense.  Done.

2022-01-08 16:26 UTC, merged

2022-01-12 16:10 UTC, vinckr commented
Hello @mritalian 
Congrats on merging your first PR in Ory 🎉 !
Your contribution will soon be helping secure millions of identities around the globe 🌏. 
As a small token of appreciation we send all our first time contributors a gift package to welcome them to the community. 
[Please drop me an email to claim your Ory swag!](mailto:vincent@ory.sh)