feat: make the password policy more configurable
ory/kratos pull request #2118
Opened 2022-01-07 00:17 UTC by RamiBerm

Added two new password config fields: `min_password_length` and `identifier_similarity_check_enabled`.

## Related issue(s)
#970

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

## Further Comments

2022-01-15 18:14 UTC, aeneasr requested changes
Sorry for the late review! This looks great! I think we should still enforce a lower limit for password length (e.g. 6).

Also could you please add a guide that explains how to use this feature in the docs/docs/guide directory? :)

2022-01-16 20:22 UTC, RamiBerm commented
@aeneasr I've added a guide and reduced the default password length to 6

2022-01-17 09:36 UTC, zepatrik requested changes

2022-01-17 09:36 UTC, zepatrik commented on embedx/config.schema.json
> +                      "default": 6
Please make the default `8`. We changed the default to be 8 in #2009, and it had quite some implications especially for automated tests and the login UI, so I would like to keep that default value.

2022-01-17 09:36 UTC, zepatrik commented on driver/config/config.go
> +		MinPasswordLength:                uint(p.p.IntF(ViperKeyPasswordMinLength, 6)),
```suggestion
		MinPasswordLength:                uint(p.p.IntF(ViperKeyPasswordMinLength, 8)),
```

2022-01-17 09:36 UTC, zepatrik commented on docs/docs/guides/password-policy.mdx
> +      min_password_length: 6
```suggestion
      min_password_length: 8
```

2022-01-17 09:36 UTC, zepatrik commented on docs/docs/guides/password-policy.mdx
> +The minimum length of the password. The default value is `6`.
```suggestion
The minimum length of the password. The default value is `8`.
```

2022-01-17 15:08 UTC, zepatrik approved these changes
Nice, thank you :+1:

2022-01-18 13:58 UTC, merged

2022-01-18 14:00 UTC, kszafran commented
Thanks from me, too ❤️. We were just discussing a need for this functionality internally.

2022-01-18 15:29 UTC, vinckr commented
Hello @kszafran 
Congrats on merging your first PR in Ory 🎉 !
Your contribution will soon be helping secure millions of identities around the globe 🌏. 
As a small token of appreciation we send all our first time contributors a gift package to welcome them to the community. 
[Please drop me an email to claim your Ory swag!](mailto:vincent@ory.sh)

2022-01-18 15:31 UTC, kszafran commented
@vinckr I'm just happy this got merged. The PR was authored by @RamiBerm. 😅