fix: upgrade guide 0.5->0.8
ory/kratos pull request #2132
Opened 2022-01-10 18:12 UTC by vinckr

As suggested in 
https://github.com/ory/kratos/discussions/2104
this 
- updates UPGRADE.md with some highlevel information on the breaking changes and links to the respective sections in the CHANGELOG for quick reference
- adds a document upgrade.md in the /docs under "Debug & Help".
I thought it makes more sense there, since it is not a very common occurance and the guide is not very extensive (yet). 

I had trouble recreating a proper upgrade scenario to test everything using the quickstart or my own deployment, so I am hoping from some input.

## Related issue(s)

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

## Further Comments

2022-01-10 20:37 UTC, aeneasr commented on UPGRADE.md
>  These changes have not yet been released and this area's purpose is to keep
I think we can probably remove this file as it no longer serves a purpose (I don't think anyone is on version 0.3.0)

2022-01-10 20:39 UTC, aeneasr commented on docs/docs/debug/upgrade.md
> +Generally after upgrading just run `kratos migrate`.
Please always warn before upgrades:

1. Explain the process
2. Make clear that they should run it against a test env first
3. Make a backup
4. Run the process itself

2022-01-10 20:39 UTC, aeneasr commented on docs/docs/debug/upgrade.md
> +Please note the following breaking changes when upgrading from Ory Kratos 0.5 to
I would suggest to just link to the changelog document here, otherwise we'll have to keep this doc here in snyc.

2022-01-10 20:39 UTC, aeneasr commented on docs/sidebar.json
> +      "debug/upgrade"
Please move this to "guides"

2022-01-10 20:39 UTC, aeneasr commented on docs/docs/debug/upgrade.md
> +title: Ory Kratos Upgrade Guide
The user already knows that they are looking at kratos. How about: "Applying Upgrades"

2022-01-10 20:40 UTC, aeneasr commented on docs/docs/debug/upgrade.md
> +Generally after upgrading just run `kratos migrate`.
Please also look at `kratos help migrate sql`, I am sure you can use some info from there :) You can also link to the command in the CLI reference.

2022-01-11 12:53 UTC, vinckr commented
First push was very low quality, should have been a draft PR 🙈.

I addressed your feedback, thanks for the pointers.

2022-01-11 13:03 UTC, aeneasr commented on UPGRADE.md
> +## v0.8.0-alpha.1
I suggest to simply delete this file! Make sure to remove it from any links as well.

2022-01-11 13:05 UTC, aeneasr requested changes

2022-01-11 13:05 UTC, aeneasr commented on docs/docs/guides/upgrade.md
> +[Ory Cloud](https://www.ory.sh/docs/#ory-cloud).
```suggestion
[Ory Cloud](https://www.ory.sh/).
```

2022-01-11 13:05 UTC, aeneasr commented on docs/docs/guides/upgrade.md
> +- **[Ory Kratos v0.5 Breaking changes](https://github.com/ory/kratos/blob/v0.5.0-alpha.1/CHANGELOG.md#breaking-changes)**
If you make new lines between list items, you create 4 individual lists. List items that belong together do not have newlines in between:

```suggestion
- **[Ory Kratos v0.8 Breaking changes](https://github.com/ory/kratos/blob/v0.8.0-alpha.1/CHANGELOG.md#breaking-changes)**
- **[Ory Kratos v0.7 Breaking changes](https://github.com/ory/kratos/blob/v0.7.0-alpha.1/CHANGELOG.md#breaking-changes)**
- **[Ory Kratos v0.6 Breaking changes](https://github.com/ory/kratos/blob/v0.6.0-alpha.1/CHANGELOG.md#breaking-changes)**
- **[Ory Kratos v0.5 Breaking changes](https://github.com/ory/kratos/blob/v0.5.0-alpha.1/CHANGELOG.md#breaking-changes)**
```

https://www.markdownguide.org/basic-syntax/#lists-1

2022-01-11 13:05 UTC, aeneasr commented on docs/docs/guides/upgrade.md
> +7. Run the upgrade on production.
Please format this correctly:

https://www.markdownguide.org/basic-syntax/#lists-1

2022-01-12 08:10 UTC, vinckr commented
Deleted UPGRADE.md and addressed the other feedback 👍

2022-01-14 14:55 UTC, aeneasr approved these changes
Great job @vinckr ! The plan is 👍

2022-01-14 14:55 UTC, aeneasr commented
@vinckr could you do this for the other projects as well?

2022-01-14 14:55 UTC, merged

2022-01-14 16:51 UTC, vinckr commented
> @vinckr could you do this for the other projects as well?

On the list 👍