feat: add configurable timeout for unsent messages
ory/kratos pull request #2257
Opened 2022-02-24 17:34 UTC by jonas-jonas

## Related issue(s)

This PR resolves https://github.com/ory/kratos/issues/944

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

## Further Comments

Open Points: 
1. I had some troubles getting all the tests to pass (even before my changes) locally. Maybe this is known already? (Errors where related to TLS handshake timeouts in `TestCompleteLogin` and a few others.)
2. I couldn't figure out how to add tests that test if something was written to the database. Do you have any pointers on that?
3. Is there documentation where I need to add the new configuration key `courier.message_ttl`?

2022-02-24 17:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/kratos?pullRequest=2257) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/kratos?pullRequest=2257) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/kratos?pullRequest=2257) it.</sub>

2022-02-26 13:40 UTC, jonas-jonas commented
Hi @Benehiko

thanks for the detailed answer. I have added a few tests to the relevant classes. I also added the key to the `config.schema.json` file. 

This should be everything and the PR is ready-for-review.

2022-02-28 03:49 UTC, Benehiko requested changes
This looks very thorough! Very nicely done :)

I have a few comments to improve this PR:
- We need a check in the persistence layer to not query abandoned projects. Somewhere [here](https://github.com/ory/kratos/blob/master/persistence/sql/persister_courier.go#L27-L39). This also means a corresponding test to make sure the `courier.NextMessages` function does not return abandoned messages.
- We need configuration tests [here](https://github.com/ory/kratos/blob/master/driver/config/config_test.go) and [here](https://github.com/ory/kratos/tree/master/test/schema). 

Other than that I think this is quite close to being merged

2022-02-28 03:49 UTC, Benehiko commented on embedx/config.schema.json
>          "smtp": {
Nice! :)

2022-03-07 08:29 UTC, jonas-jonas commented
> We need a check in the persistence layer to not query abandoned projects. Somew[here](https://github.com/ory/kratos/blob/master/persistence/sql/persister_courier.go#L27-L39) here. This also means a corresponding test to make sure the courier.NextMessages function does not return abandoned messages.

That method already only queries messages that have the `status=MessageStatusQueued`. I think that should exclude messages that have the `status= MessageStatusAbandoned` (or any other `MessageStatus` for that matter). This is also tested [here](https://github.com/ory/kratos/blob/b1f270c12e7193f3d2abb65947ed92c1906ee69c/courier/test/persistence.go#L93-L95) by manually setting the `status` of a message to Abandoned and then checking the result to be empty. Am I missing something here?


>We need configuration tests [here](https://github.com/ory/kratos/blob/master/driver/config/config_test.go) and [here](https://github.com/ory/kratos/tree/master/test/schema).

I will add the tests later today.

2022-03-07 08:40 UTC, Benehiko commented
> > We need a check in the persistence layer to not query abandoned projects. Somew[here](https://github.com/ory/kratos/blob/master/persistence/sql/persister_courier.go#L27-L39) here. This also means a corresponding test to make sure the courier.NextMessages function does not return abandoned messages.
> 
> That method already only queries messages that have the `status=MessageStatusQueued`. I think that should exclude messages that have the `status= MessageStatusAbandoned` (or any other `MessageStatus` for that matter). This is also tested [here](https://github.com/ory/kratos/blob/b1f270c12e7193f3d2abb65947ed92c1906ee69c/courier/test/persistence.go#L93-L95) by manually setting the `status` of a message to Abandoned and then checking the result to be empty. Am I missing something here?
> 
> > We need configuration tests [here](https://github.com/ory/kratos/blob/master/driver/config/config_test.go) and [here](https://github.com/ory/kratos/tree/master/test/schema).
> 
> I will add the tests later today.

Ah yes, sorry about that. You are correct :)

2022-03-07 20:41 UTC, jonas-jonas commented
I added the config tests. This should be everything.

2022-03-08 09:15 UTC, zepatrik approved these changes
Nice, looks good to me :+1: 
Waiting for @Benehiko to confirm.

2022-03-08 09:15 UTC, zepatrik commented on courier/test/persistence.go
> +			require.NoError(t, p.SetMessageStatus(ctx, messages[0].ID, courier.MessageStatusAbandoned))
Ah, I see. The persister already only gets pending ones.

2022-03-08 09:37 UTC, Benehiko approved these changes
LGTM :)

Really nicely done!

2022-03-08 09:39 UTC, merged

2022-03-09 13:57 UTC, vinckr commented
Hello @jonas-jonas 
Congrats on merging your first PR in Ory 🎉 !
Your contribution will soon be helping secure millions of identities around the globe 🌏. 
As a small token of appreciation we send all our first time contributors a gift package to welcome them to the community. 
[Please drop me an email and I will forward you the form to claim your Ory swag!](mailto:vincent@ory.sh)