feat: add seach engine
ory/kratos pull request #2442
Opened 2022-05-02 14:46 UTC by david972

This feature is for adding the capability to use query parameter to filter identities result on `/identities` handler.

For now couple things to do :

- Review the paging
- Add identifier in the search field
- update the documentation 

## Related issue(s)

#1278 
replace (rebase with master) #1671

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

2022-05-02 14:47 UTC, david972 commented
need a help here
found duplicate entries into response

2022-05-13 15:58 UTC, aeneasr requested changes
Thank you!!

I think there are some issues with potential SQL injections. We also need to add many more tests, preferably also fuzzing tests ( https://go.dev/doc/fuzz/ ) for the input parameters.

Additionally, we will need a dedicated test suite for `persister_identity.go` and we need to update the documentation :)

A good place to add documentation for this feature would be in: https://github.com/ory/docs/tree/master/docs/guides/manage-identities

2022-05-13 15:58 UTC, aeneasr commented on persistence/sql/persister_identity.go
> +}
These are complex functions but they do not have any tests. Can you please add unit tests to ensure that these behave the way you want?

2022-05-13 15:58 UTC, aeneasr commented on persistence/sql/persister_identity.go
> +			return q
@zepatrik what do you think about this? It's basically SQL injection, but with some sanization in front (see `!validFields.MatchString(field)`). I'm not 100% convinced though yet that we should merge it as is. Can you PTAL?

2022-05-13 15:58 UTC, aeneasr commented on persistence/sql/persister_identity.go
> +				q = q.Where(fmt.Sprintf(`%s @> ?`, prefix), param)
This in particular is potentially dangerous as the prefix is not escaped.

2022-05-13 15:58 UTC, aeneasr commented on persistence/sql/persister_identity.go
> +					q = q.Where(fmt.Sprintf(`json_extract(%s, '$.%s') = ?`, prefix, key), value)
Same here, otherwise it allows to use commands like `GRANT` or `NOW()` here

2022-05-13 15:58 UTC, aeneasr commented on persistence/sql/persister_identity.go
> +					q = q.Where(fmt.Sprintf(`json_extract(%s, '$') = ?`, prefix), value)
The `%s` should be escaped, something like:

```suggestion
					q = q.Where(fmt.Sprintf(`json_extract(`%s`, '$') = ?`, prefix), value)
```

2022-05-13 16:00 UTC, aeneasr commented
Another question - have you been able to test how performant this is when you have, let's say, 1 million identities loaded? I could imagine it being very slow / timing out for a certain store size :/ Can we use some type of index to speed up the lookup?

2022-05-14 07:15 UTC, david972 commented
> Another question - have you been able to test how performant this is when you have, let's say, 1 million identities loaded? I could imagine it being very slow / timing out for a certain store size :/ Can we use some type of index to speed up the lookup?
maybe 
on `traits` it could be hard but on the other yes
I'll have a look

2022-06-29 19:20 UTC, Sytten commented
Anything we can do to help merge that? This is really a big piece missing right now from the API

2022-06-29 19:36 UTC, david972 commented
> Anything we can do to help merge that? This is really a big piece missing right now from the API

Hi
Just need some help because this implementation returns duplicate results 
And more tests needs too

2022-07-04 10:57 UTC, aeneasr commented
The biggest challenge this PR faces is computing the query SQL correctly without the risking SQL injection. Another problem is one of performance as the indices required will quickly grow out of hand at scale. It might work for limited use cases but in general we need to:

1. Implement robust SQL validation
2. Add more tests
3. Improve queries
4. Verify scalability

2022-07-20 23:28 UTC, ofairfoul commented
Would it be possible to simply expose FindByCredentialsIdentifier on the Admin Identity API?
I think this would meet the needs of the majority of people who just want to find usernames(emails) which are already registered.
e.g. https://developer.okta.com/docs/reference/api/users/#get-user-with-login

2022-07-21 12:18 UTC, kmherrmann commented
IMHO we should scope this clearly to 

1. retrieval by credentials identifier as suggested in https://github.com/ory/kratos/pull/2442#issuecomment-1190867502
2. simple prefix/infix/regex(?) matching on identifiers
3. powerful full text search

If we're after (3), I believe we should explore using a dedicated backend like Elastic Search for the purpose, which can easily handle large data sets and can do scoring and ranking properly.

2022-07-22 01:47 UTC, jonnyijapan commented
This is interesting - would it be possible to add exactly what new features this PR would introduce in the top post? Like would it be possible to use the API as a lookup, like "get the identity having this credential identifier: 'test@test.xxx' ?

2022-07-24 21:23 UTC, kmherrmann commented
> This is interesting - would it be possible to add exactly what new features this PR would introduce in the top post? Like would it be possible to use the API as a lookup, like "get the identity having this credential identifier: '[test@test.xxx](mailto:test@test.xxx)' ?

This PR, IIUC, introduces (2), using additional SQL conditions. That's useful, but won't scale to (3) and (4) and comes with the mentioned security and performance caveats. 

A getByCredentialIdentifier equivalent (option 1) that's optimized for performance (maybe indexed columns and exact matching?) sounds like a good addition to me when used in serving (vs. administrative / support tools).

2022-10-04 12:41 UTC, aeneasr commented
After much consideration, I think that we can't move forward with the PR as is. The problem is that this functionality will work at very low scale but quickly erode in performance as we hit 1M+ entries. In the end, the database will need to load all rows into RAM, parse JSON, and match the fields. This just won't work at volume.

I'm open to have dedicated search for specific fields (such as verified address) but identity traits are out of the question. We'll need to do another set up with elastic or something similar instead.

2022-10-04 12:42 UTC, aeneasr commented
Sorry for all the work you have put in @david972 . I think it's per-se a great PR, but the task at hand is much bigger than what we thought initially. There are so many edge cases to cover (fuzzing, sql injection, performance), that this will need a much larger architectural effort involving proven technologies (elastic, lucene, ...) to offer something that can scale.

Sending out much Ory love :)

2022-10-04 12:42 UTC, closed without merging

2022-10-04 12:44 UTC, david972 commented
Hi I understand
maybe we can just open a discussion on how to do it properly ?

2022-10-04 12:45 UTC, aeneasr commented
Absolutely!

2022-10-16 02:31 UTC, zFlux commented
@aeneasr @kmherrmann - it sounds like @kmherrmann 's option 1) implementing @ofairfoul 's suggestion i.e. expose FindByCredentialsIdentifier on the Admin Identity API (so long as we're ensuring exact match only and index use) is still ok to attempt a PR on?

2022-10-16 07:26 UTC, david972 commented
transferred here #2783