fix: do not check csrf if it's not set in verification flow
ory/kratos pull request #2455
Opened 2022-05-10 06:01 UTC by splaunov

When user clicks the verification link sent over email and the link has expired, then Kratos creates new verification flow and browser is redirected to verification ui with the new flow id set as a URL parameter.
The problem is that the verification UI cannot fetch the new flow as it has no csrf token set. So, browser gets 403 "Forbidden" error.

This PR eliminates csrf checking if verification flow has no csrf token.

## Related issue(s)

## Checklist

- [ x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [ x] I have read the [security policy](../security/policy).
- [ x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

## Further Comments

2022-05-13 10:09 UTC, aeneasr requested changes

2022-05-27 19:09 UTC, aeneasr commented
While the PR is being worked on I will mark it as a draft. That declutters our review backlog :)

Once you're done with your changes and would like someone to review them, mark the PR as ready and request a review from one of the maintainers.

Thank you!

2022-09-02 14:57 UTC, splaunov commented on selfservice/flow/verification/handler.go
> +	if req.Type == flow.TypeBrowser && req.CSRFToken != "" && !nosurf.VerifyToken(h.d.GenerateCSRFToken(r), req.CSRFToken) {
Have extended test to cover this case and added token regeneration to the expired flow error handling logic.

2022-11-01 12:57 UTC, aeneasr submitted a review, later dismissed

2022-11-01 12:57 UTC, aeneasr commented
@jonas-jonas do we need to do this in the code strategy too?

2022-11-01 12:58 UTC, aeneasr commented
@splaunov sorry for the late review, I am just catching ip on PRs! If the merge conflicts are addressed I will merge this immedia!

2022-11-02 14:25 UTC, jonas-jonas commented
Yes, recovery should need that too: https://github.com/ory/kratos/blob/master/selfservice/flow/recovery/error.go#L82

I can take a look, or if you want to do it, you can do that in here. @splaunov :)

2022-12-27 15:52 UTC, splaunov commented
The fix has been merged form some other branch.
Only the test change has been left not merged.

2022-12-29 08:37 UTC, aeneasr approved these changes

2022-12-29 08:37 UTC, merged