feat(tracing): improved tracing for requests and persistence
ory/kratos pull request #2475
Opened 2022-05-17 13:10 UTC by icyphox

This PR introduces improved tracing using OpenTelemetry, with traces (enriched with attributes) for every endpoint and its underlying database operations. Merging https://github.com/ory/x/pull/511 before this would be ideal, as it adds an ignore filter for Kratos' `/admin/health/*` endpoints.

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

2022-05-19 11:02 UTC, zepatrik commented on persistence/sql/persister_courier.go
> +		ctx, span := p.r.Tracer(ctx).Tracer().Start(ctx, "persistence.sql.NextMessages")
What is the difference here? It should be the same right?

2022-05-19 12:29 UTC, zepatrik submitted a review, later dismissed

2022-05-19 13:07 UTC, aeneasr requested changes
Can you add tracing to the hashers please as well?

We also need tracing for webhooks / external HTTP calls

2022-05-20 06:43 UTC, aeneasr approved these changes

2022-05-20 07:35 UTC, merged