add identity id to "account disabled" error
ory/kratos pull request #2557
Opened 2022-06-30 15:31 UTC by splaunov

When user tries to login with oidc and encounters "account disabled" error it is hard to find which identity is inactive.
oidc provider user id (subject) is needed to find the identity.

To make this simpler, this PR adds identity id to the logs.

## Related issue(s)

## Checklist

- [ x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ x] I am following the [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [ x] I have read the [security policy](../security/policy).
- [ x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security. vulnerability, 
      I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

## Further Comments

2022-07-01 11:33 UTC, zepatrik approved these changes

2022-07-01 11:37 UTC, zepatrik requested changes
It looks like you have to adjust these two assertions: https://github.com/ory/kratos/blob/3b640ca985b1b22bd1145c7d6feeec5966c39ef3/selfservice/strategy/link/strategy_recovery_test.go#L405-L409

2022-07-11 15:07 UTC, splaunov commented
Have fixed the test. Sorry for the delay.

2022-07-12 06:46 UTC, aeneasr approved these changes

2022-07-12 06:47 UTC, merged

2022-07-13 06:57 UTC, vinckr commented
Hello @splaunov   
Congrats on merging your first PR in Ory 🎉 !
Your contribution will soon be helping secure millions of identities around the globe 🌏. 
As a small token of appreciation we send all our first time contributors a gift package to welcome them to the community. 
[Please drop me an email and I will forward you the form to claim your Ory swag!](mailto:vincent@ory.sh)