Preserve return_to param between flows
ory/kratos pull request #2644
Opened 2022-08-05 12:17 UTC by mmeller-wikia

## Related issue(s)

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I am following the [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security. vulnerability, 
      I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

## Further Comments

2022-08-05 12:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/kratos?pullRequest=2644) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/kratos?pullRequest=2644) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/kratos?pullRequest=2644) it.</sub>

2022-08-19 06:08 UTC, mmeller-wikia commented
Hi @aeneasr 
Can I ask for review?
I think that failing checks are not related to my changes ;)

2022-08-23 15:47 UTC, aeneasr requested changes
Thank you, great job! Can you please provide a failing test case for the bug you observed to prove that this change is effective?

2022-08-23 15:47 UTC, aeneasr commented on x/http_secure_redirect.go
> +func TakeOverReturnToParameter(from string, to string) (string, error) {
Can you please add a test for this?

2022-10-04 12:33 UTC, aeneasr approved these changes

2022-10-04 12:33 UTC, merged

2022-10-04 12:33 UTC, aeneasr commented
Awesome, thank you! 🎉 Your contribution makes Ory better :)

2022-10-12 10:59 UTC, vinckr commented
Hello @mmeller-wikia 
Congrats on merging your first PR in Ory 🎉 !
Your contribution will soon be helping secure millions of identities around the globe 🌏. 
As a small token of appreciation we send all our first time contributors a gift package to welcome them to the community. 
[Please drop me an email and I will forward you the form to claim your Ory swag!](mailto:vincent@ory.sh)