implement offline scope in the way google expects
ory/kratos pull request #3088
Opened 2023-02-09 14:39 UTC by tsearle

google doesn't implements offline access as a scope but instead as a special uri parameter

this PR adapts the code such that if the offline_access scope is requested, it gets transformed into the parameter
access_type=offline

2023-02-09 14:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/kratos?pullRequest=3088) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/kratos?pullRequest=3088) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/kratos?pullRequest=3088) it.</sub>

2023-02-09 15:19 UTC, tsearle commented
linked issue
https://github.com/ory/network/issues/242

2023-02-10 13:14 UTC, aeneasr commented on selfservice/strategy/oidc/provider_google.go
> +	}
Not sure if I understand this - if the scope is not "offline_access", we automatically add it? Is that really what we want?

2023-02-10 13:16 UTC, tsearle commented
indeed it should be the inverse
I'll fix it


On Fri, Feb 10, 2023 at 2:14 PM hackerman ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In selfservice/strategy/oidc/provider_google.go
> <https://github.com/ory/kratos/pull/3088#discussion_r1102754139>:
>
> > +	if !stringslice.Has(scope, gooidc.ScopeOfflineAccess) {
> +		options = append(options, oauth2.AccessTypeOffline)
> +	}
>
> Not sure if I understand this - if the scope is not "offline_access", we
> automatically add it? Is that really what we want?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ory/kratos/pull/3088#pullrequestreview-1293154503>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABCUPI4Z4ZA56Z6RD26KVVDWWY5MTANCNFSM6AAAAAAUWUJ7T4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-02-10 13:16 UTC, aeneasr requested changes
Awesome, thank you for your contribution! This looks pretty good and I have some ideas how to improve it further :)

2023-02-10 13:16 UTC, aeneasr commented on selfservice/strategy/oidc/provider_google.go
> +	}
You can simplify this by calling `options := g.ProviderGenericOIDC.AuthCodeURLOptions()` and then add your custom logic afterwards :)

2023-02-10 13:16 UTC, aeneasr commented on selfservice/strategy/oidc/provider_google.go
> +		Scopes:       stringslice.Filter(scope, func(s string) bool { return s == gooidc.ScopeOfflineAccess }),
please add below line 34 for better readability :)

2023-02-10 13:17 UTC, aeneasr commented
Maybe you can add a small test that shows that the offline access thing is correctly configured when the scope is set? :)

2023-02-14 16:14 UTC, merged

2023-02-14 16:14 UTC, aeneasr commented
Thank you for making Ory better :)