feat: show "continue" screen after successful verification
ory/kratos pull request #3090
Opened 2023-02-10 12:17 UTC by jonas-jonas

The `link` strategy for verification now shows a confirmation screen with a "continue" link after successful verification, aligning its behavior to the `code` strategy.

Also fixes a bug, where the `default_browser_return_url` of the verification flow was not respected when using the code strategy.

## Related issue(s)

Closes ory-corp/cloud#3925
Fixes ory/network#228
Fixes https://github.com/ory/network/issues/224

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

## Further Comments

https://user-images.githubusercontent.com/5540255/218118857-9fdefc4e-afce-4798-86d6-409b073b2b4f.mov

(_The red color of the confirmation stems from an outdated version of the kratos selfservice example UI. This is fixed in current versions of the repo_).

2023-02-10 14:49 UTC, jonas-jonas commented on selfservice/strategy/link/strategy_verification_test.go
> +				res, err := client.Get(public.URL + verification.RouteSubmitFlow + "?" + url.Values{"flow": {flow.ID.String()}, "token": {token.Token}}.Encode())
`Get`ing the link matches more closely, what a user would do (e.g. opening the link in a browser).

2023-02-13 10:22 UTC, Benehiko commented on selfservice/flow/verification/flow_test.go
> +			desc: "return_to has precendence over global return to",
```suggestion
			desc: "return_to has precedence over global return to",
```

2023-02-13 10:24 UTC, Benehiko commented on selfservice/flow/verification/flow_test.go
> +			desc: "flow return to has precendence over global return to",
```suggestion
			desc: "flow return to has precedence over global return to",
```

2023-02-13 10:24 UTC, Benehiko commented on selfservice/flow/verification/flow_test.go
> +			desc: "return_to has precendence over flow return to",
```suggestion
			desc: "return_to has precedence over flow return to",
```

2023-02-13 10:56 UTC, Benehiko requested changes
Small nits, but other than that this PR is good :)

2023-02-13 12:34 UTC, Benehiko approved these changes
Very nice! :)

2023-02-13 15:14 UTC, aeneasr approved these changes

2023-02-13 15:23 UTC, merged