fix: use RETURNING clause for batch create
ory/kratos pull request #3293
Opened 2023-05-26 08:56 UTC by aeneasr

`batch.Create` regressed on gobuffalo/pop improvements that use `RETURNING` clauses and `gen_random_uuid()`. This patch addresses that

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.

2023-05-26 20:47 UTC, aeneasr commented
Added some comments, all tests pass now. Should be good to go!

2023-05-30 08:00 UTC, alnr requested changes
Nice! Small nit

2023-05-30 08:00 UTC, alnr commented on persistence/sql/batch/create.go
> +func buildInsertQueryArgs[T any](ctx context.Context, dialect string, mapper *reflectx.Mapper, quoter quoter, models []*T) (insertQueryArgs, error) {
`buildInsertQueryArgs` never returns an error I think.

2023-05-30 08:02 UTC, aeneasr commented on persistence/sql/batch/create.go
> +func buildInsertQueryArgs[T any](ctx context.Context, dialect string, mapper *reflectx.Mapper, quoter quoter, models []*T) (insertQueryArgs, error) {
true, probably an artifact form playing around with reflection. Will fix

2023-05-30 09:25 UTC, alnr approved these changes

2023-05-30 11:32 UTC, hperl approved these changes
LGTM!

2023-05-30 11:37 UTC, merged