Add support for Proof Key For Code Exchange (PKCS) in OIDC social providers
ory/kratos pull request #4033
Opened 2024-08-13 09:05 UTC by OskarsPakers

Adds support for Proof Key For Code Exchange (PKCS) in OIDC social providers according to rfc7636 https://datatracker.ietf.org/doc/html/rfc7636

## Related issue(s)

#4009 

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](https://github.com/ory/docs).

## Further Comments

Supports methods s256 and plain.
AuthCodeURLOptions method signature does not return err, therefore can`t return an error. Should we change the signature of the method and lift the functionality up to the strategy code?

2024-08-13 09:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/kratos?pullRequest=4033) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/kratos?pullRequest=4033) before we can accept your contribution.<br/><hr/>**EriksP** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/kratos?pullRequest=4033) it.</sub>

2024-08-19 07:07 UTC, hperl requested changes
Thank you for your contribution! This looks very good already. I have added some comments below, mostly to make sure that this code also works for registration and settings flows.

Also, I'd like to see more tests on this. So far, I could only see unit tests for the provider. We also need E2E tests that make sure that the challenge and verifier are correctly persisted and compared, with both happy and error paths covered.

2024-08-19 07:07 UTC, hperl commented on selfservice/strategy/oidc/strategy.go
> +					return nil, errors.Errorf("Invalid PKCS method: %s or empty verifier: %s", pkcsContext.Method, pkcsContext.Verifier)
This should be a `herodot` error as well.

2024-08-19 07:07 UTC, hperl commented on selfservice/strategy/oidc/strategy_login.go
> +	if provider.Config().PKCSMethod != "" {
This also needs to be done for registration. And how about settings?

2024-09-04 07:49 UTC, OskarsPakers commented
Closing this one as it seems to be continued in https://github.com/ory/kratos/pull/4033

2024-09-04 07:49 UTC, closed without merging