Update sign-in-with-github-google-facebook-linkedin.mdx
ory/kratos pull request #687
Opened 2020-09-03 11:59 UTC by kushalbigapp

oidc.google.jsonnet file can be kept same as the github or microsoft provider for simplicity

## Related issue

## Proposed changes

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

## Further comments

2020-09-03 12:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/kratos?pullRequest=687) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/kratos?pullRequest=687) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/kratos?pullRequest=687) it.</sub>

2020-09-07 12:46 UTC, aeneasr approved these changes

2020-09-07 12:47 UTC, aeneasr requested changes

2020-09-07 12:47 UTC, aeneasr commented on docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx
> + - id: google
Looks like the formatting got a bit funky here :)

2020-10-01 11:47 UTC, vinckr approved these changes

2020-10-02 06:39 UTC, aeneasr commented
Thank you, this looks great! Could you please sign the CLA (just two clicks), then we can merge it right away!

2020-10-13 09:59 UTC, closed without merging